
theme = "catppuccin_frappe"

[editor]
line-number = "relative"
cursorline = true
color-modes = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.indent-guides]
render = true

[keys.insert]
j = { k = "normal_mode" } # Maps `jk` to exit insert mode
